### PR TITLE
Added 500/400 pages, refactored to separate footer.njk.

### PR DESCRIPTION
**Pull request by chadcurtis**
Separated the footer into footer.njk. #10 

I've also fixed the error with index.njk. Nunjucks has issues taking '{{}}' as plain text, lest it is formatted as such:
**{% raw %}{{ a philly house on a mission }}{% endraw %}**

The 400/500 pages need clean-up, but they're a start. #20

### CODE REVIEW

**Comment by alexgleason** [comment]
Thanks! Will review soon. Ideally this is separated into 3 commits.

**Comment by marykatefain** [comment]
Ohhh that makes sense! Nice catch!

**Comment by chadcurtis** [comment]
@alexgleason Noted, I'll try to keep that in mind for future commits.

Formatting aside, does this work? Is it fine to commit?

**Comment by alexgleason** [comment]
Sorry still need to pull and look

**Comment by alexgleason** [comment]
This doesn't make any sense. 400.njk and 500.njk are identical. 4040.njk isn't an HTTP error and contains what 500.njk probably should have. Also, don't use any nunjucks in the 500 page. Make it called 500.html and embed any css or js right in. This is because a 500 error could occur within Wick itself and could be related to the rendering engine so we should rely on it as little as we can. the 500 page should be its own thing entirely and not contain any nav etc.

Finally this text is far from legible. It needs to meet WCAG specs but as it stands even an able person cannot read it.

screenshot from 2017-05-25 17 53 45

**Comment by chadcurtis** [comment]
That was sloppy, the 4040.njk was an artifact of attempting to copy the 404.njk as a base. I apologize for such shoddiness. Anyway, here is the present styling. Feel free to review further.

**Comment by chadcurtis** [comment]
Commit squashed. There are a few solutions (as far as I would know) to allow a custom body background color on the 404 page. The first would be to make it completely independent (akin to the 500.html page) with it's own styles. The second would be to add a `<style>{% block style %}{% endblock %}</style>` to _base.njk, and then add a style via `{% block style %} *content* {% endblock %}` to 404.njk.

At this time, I've opted for the third option: adding `class="{{ current.source }}"` to the body tag on _base.njk. However, CSS does not recognize the class `.404`, so the work around is escaping it via a unicode character. (See [here](https://benfrain.com/when-and-where-you-can-use-numbers-in-id-and-class-names/) for more info.)

There may be a more elegant solution that I'm not aware of, but I'd appreciate input on how to approach this matter, or if I should dodge around custom background coloring *period*.

**Comment by alexgleason** [comment]
Just call the class error404

**Comment by chadcurtis** [comment]
I adapted the solution from @marykatefain's system via adding `<body {% if current.source == '404' %} class="error404"{% endif %}>` in _base.njk. This is the next cleanest way of specifically attributing a body class to the 404 page.

**Comment by alexgleason** [comment]
Squash the commits

**Comment by chadcurtis** [comment]
Done and done.

**Comment by alexgleason** [comment]
Looks great, thank you!

**Pull request merged**
